### ISSUE TITLE
Before Router Middlewares not working for root

### ISSUE THREAD

**Issue by aiamk** [bramus/router#45] opened 2017-09-20 04:55 UTC
I tried the following example and it works on all paths except the root "/"

$router->before('GET', '/.*', function() {
    // ... this will always be executed
});

**Comment by bramus** [comment] 2017-10-06 17:17
I've just expanded the tests to [also test a `GET` on `/`](https://github.com/bramus/router/commit/b7c7c76a54ca5f2c5843bf37f363b40e95fc1a43#diff-865750edcb7db8ffb18c22c2696e4b56R495). The test returns no error.

**Comment by bramus** [comment] 2017-10-06 17:21
Running the included demo from the `demo` folder also yields a proper result:

```
$ curl -I -X GET http://localhost:8080
HTTP/1.1 200 OK
Host: localhost:8080
Connection: close
X-Powered-By: bramus/router
Content-type: text/html; charset=UTF-8
```

The `X-Powered-By` header is injected using a before middleware:

```
$router->before('GET', '/.*', function () {
    header('X-Powered-By: bramus/router');
});
```

➡ Closing this one as I cannot reproduce it.

**Closed by bramus** 2017-10-06 17:21 UTC
